# Generated by Django 4.1.5 on 2023-01-17 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medidor', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicion',
            unique_together={('fecha_hora', 'medidor')},
        ),
    ]
